# Version de l'API Docker Compose à utiliser pour lire ce fichier
version: '3.8'

# Déclaration des services
services:

  my_app:
    build:
      context: ./wik-dps-tp02-correction-rust/
      dockerfile: multi-stage.dockerfile

    # ports:
    #   - '8080:8080'

    expose: 
      - '8080'
    
    deploy:
      replicas: 4 
    
    restart: always

    environment:
      - PING_LISTEN_PORT=8080
    
    networks:
      - front-network
  
  # Un service nommé proxy
  proxy:

    environment:
      - PING_LISTEN_PORT=8080
    
    image: nginx:latest

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

    ports:
      - 8081:80

    depends_on: 
      - my_app
    
    networks:
      - front-network


# Déclaration des réseaux
networks:
  # Un network nommé front-network qui utilise le driver bridge
  front-network:
    driver: bridge

# Déclaration des volumes nommés
volumes:
  db_data: